vim.cmd 'colorscheme gruvbox-material'

vim.cmd.hi 'Normal guibg=none'
vim.cmd.hi 'NormalFloat guibg=none'
vim.cmd.hi 'NormalNC guibg=none'
vim.cmd.hi 'MsgArea guibg=none'
vim.cmd.hi 'ColorColumn guibg=darkred'
vim.cmd.hi 'FloatBorder guibg=none'
vim.cmd.hi 'Comment guifg=grey'
vim.cmd.hi 'MatchParen guibg=grey'
vim.cmd.hi 'LineNr guibg=#32302f guifg=grey'
vim.cmd.hi 'SignColumn guibg=#32302f'
