DefineNeovimColors = function()
  vim.cmd.colorscheme 'ofirkai'
  vim.opt.colorcolumn = '80'
  vim.cmd.hi 'ColorColumn guibg=#5d1b1c'
  -- vim.cmd.hi 'Normal guibg=#242424'
  vim.cmd.hi 'StatusLine guibg=#D8D6C9 guifg=black gui=bold'
  -- vim.cmd.hi 'Normal guibg=#181818 guifg=#D8D6C9'
  -- vim.cmd.hi 'Normal guibg=#1E1E1E guifg=#D8D6C9'
  vim.cmd.hi 'Normal guibg=none'
  vim.cmd.hi 'SignColumn guibg=none'
  vim.cmd.hi 'LineNr guifg=NvimLightgreen guibg=none gui=bold'
  vim.cmd.hi 'LineNrAbove guifg=grey'
  vim.cmd.hi 'LineNrBelow guifg=grey'
  vim.cmd.hi 'Statement guifg=pink gui=bold'
  vim.cmd.hi 'Constant guifg=orange'
  -- vim.cmd.hi 'Special guifg=magenta'
  -- vim.cmd.hi 'Function guifg=#f5ee2a gui=bold'
  -- vim.cmd.hi 'Function guifg=#F14C4C gui=bold'
  vim.cmd.hi 'Visual guibg=#4D8FAC guifg=black'
  vim.cmd.hi 'Visual guibg=#264F78 guifg=white'
  vim.cmd.hi 'Directory guifg=#6A9FB5'
  vim.cmd.hi 'DiagnosticError guibg=black gui=bold guifg=red'
  vim.cmd.hi 'Question guifg=darkred'
  vim.cmd.hi 'UndotreeDiffRemoved guibg=red'
  vim.cmd.hi 'UndotreeDiffAdded guibg=pink'
  vim.cmd.hi 'Comment guifg=#32a852'
  vim.cmd.hi 'Operator guifg=white cterm=bold gui=bold'
end
